name: dt photoblog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50225
title: BlotoPhog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#3c312d'
    - '#706a66'
    - '#c0c1c0'
    - '#8f8a85'
  brandStrength: 0.5
  lightness: 0.14631026005372405
  saturation: 0.8134231679141521
  rhythmicContrast: 0.2751260264776647
purpose: []
