name: dt photoblog
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.50225
title: dt family photoblog...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#3c312d'
    - '#706a66'
    - '#c0c1c0'
    - '#8f8a85'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
